from dotenv import load_dotenv
load_dotenv()

from starter_app import app, db
from starter_app.models import User, Digimon, Media

with app.app_context():
  db.drop_all()
  db.create_all()

#####################################################################################
# USERS                                                                             #
#####################################################################################

  ian = User(username = 'Ian', email = 'ian@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')
  javier = User(username = 'Javier', email = 'javier@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')
  dean = User(username = 'Dean', email = 'dean@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')
  angela = User(username = 'Angela', email = 'angela@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')
  soonmi = User(username = 'Soon-Mi', email = 'soonmi@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')
  alissa = User(username = 'Alissa', email = 'alissa@aa.io', password = 'password', photo_url = 'https://digicyclopedia.s3.us-east-2.amazonaws.com/UserImages/default-profile-icon-17.jpg')

  db.session.add(ian)
  db.session.add(javier)
  db.session.add(dean)
  db.session.add(angela)
  db.session.add(soonmi)
  db.session.add(alissa)


######################################################################
# DIGIMON                                                            #
######################################################################
  ###   Baby    ####################################################################################
  # argomonB = Digimon(name="Argomon(Baby)", level="Baby", next_form=["Argomon(In-Training)"], bio="Argomon (Baby) is a Mutant Digimon. It is a Fresh Digimon born from a bug in an algorithm/computational program. It has a habit of finding and converging at places where high-capacity data leaks out. They gather one by one, growing into a horde and blanketing it.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Argomon_(Fresh)_b.jpg")
  # chibomon = Digimon(name="Chibomon", level="Baby", next_form=["DemiVeemon"], bio="Chibomon is a Slime Digimon, and as such, it is small and young. It is a small, blue-colored, Dragon Digimon child, and although it is small and powerless, it has the potential to digivolve to every Dragon Digimon. For that reason, it is a Digimon that is considered exceedingly valuable by tamers and researchers of Dragon Digimon. It is cherished due to its personality of friendliness and overflowing curiosity, characteristic of Fresh Digimon. Just like other Fresh Digimon, it spits acidic bubbles to attack, but as usual, their power is nonexistent.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Chibomon_b.jpg")
  # dodomon = Digimon(name="Dodomon", level="Baby", next_form=["Dorimon", "Wanyamon"], bio="Dodomon is a Slime Digimon and a carrier of the X Antibody. Its whole body is covered in a tough fur named 'Mithril Hair'. It manifests an aggressive personality immediately after being born, and despite its fangs not yet being grown, it opens its mouth wide and completely intimidates the opponent with the manner in which it snaps at them. Because of this, there exist many Digimon which are completely deceived, but it is still a rare Digimon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Dodomon_b.jpg")
  # keemon = Digimon(name="Keemon", level="Baby", next_form=["Yaamon"], bio="Keemon is a Slime Digimon. It is an evil-eyed Digimon which is always scowling. Though it's very young, it hates being crowded by others, and lives in hiding. It likes poking its nose out of hiding and harassing with its 'Pushū'.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Keemon_b.jpg")
  # ketomon = Digimon(name="Ketomon", level="Baby", next_form=["Hopmon"], bio="Ketomon is a Slime Digimon. It is a Digimon whose large eyes are its defining characteristic. These eyes have the ability to discern the nature of Digimon, allowing it to detect violent Digimon in advance and warn its allies of the danger.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Ketomon_b.jpg")
  # metalkoromon = Digimon(name="MetalKoromon", level="Baby", next_form=["Kapurimon"], bio="MetalKoromon is a Machine Digimon. It is super-tiny and has red eyes that act as photosensors. The appearance of it moving around restlessly seems very cute, but because it is carrying nothing but a simple program that moves in reaction to bright lights, if its surroundings go dark, it becomes completely unable to move. The reason why is not understood, but when it is in a good mood, it discharges electricity from the tip of its tail.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/MetalKoromon_b.jpg")
  # mokumon = Digimon(name="Mokumon", level="Baby", next_form=["DemiMeramon"], bio="Mokumon is a Smoke Digimon. It is a Digimon Baby which envelops its body with a smoke-like vapor. It is a unique Digimon whose DigiCore is bare, so it seems it covers its DigiCore with Smoke in order to protect it, and has an unusual way of life. Because the Smoke was generated when its DigiCore was burned, it seems it is harmful neither to Mokumon itself nor to others. Also, because it is still in the middle of digivolving, when it encounters an opponent, it immediately flees. Then, it scatters the Smoke issuing from its body all around, and seizes the opportunity to escape when the opponent loses sight of it. As stated earlier, because it isn't particularly harmful, if you happen to see one, it would be best to be quiet", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Mokumon_b.jpg")

  botamon = Digimon(name="Botamon", level="Baby", next_form=["Koromon", "Wanyamon"], bio="Botamon is a Slime Digimon. It was just born recently, and on the surface of its slime-shaped body, it has grown thick, black fuzz. It is unable to battle as it has just been born.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Botamon_b.jpg")
  conomon = Digimon(name="Conomon", level="Baby", next_form=["Kokomon"], bio="Conomon is a Slime Digimon. Conomon and Zerimon are extremely rare Digimon which are born in pairs from a single Digi-Egg. The reason why only Zerimon and Conomon are born as twins is unclear at the present stage. Moreover, they are not restricted to always being born as twins, and either a Zerimon or Conomon may be born from a single Digi-Egg. Compared to the extremely energetic, one-horned Zerimon, the three-horned Conomon has a relatively docile personality. Like other Fresh Digimon, it spits acid bubbles to intimidate opponents.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Conomon_b.jpg")
  jyarimon = Digimon(name="Jyarimon", level="Baby", next_form=["Gigimon"], bio="Jyarimon is a Slime Digimon. It is an extremely scarce Digimon, whose population is small. The Fresh-levels of Dragon-species Digimon are small in absolute number, and it is said that most of them are captured or die before they grow up. You wouldn't know it to look at it, but there are tiny, closely packed fangs growing within its mouth, and it is foreseen that it will grow into a powerful Dragon-species Digimon. Although it is powerless, it has the disposition to face those with bodies larger than its own, and that becomes the reason for its low survival rate.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Jyarimon_b.jpg")
  kuramon = Digimon(name="Kuramon", level="Baby", next_form=["Tsumemon", "Arcadiamon(In-Training)", "Pagumon"], bio="Kuramon is an Unidentified Digimon. It suddenly appeared on the Computer Network. Aggression, generated by the malice of people who abuse the Computer Network or the conflicts which are unfolding on the Network, manifested and a single Digi-Egg was created. Humanity's destructive instincts are condensed within that Digi-Egg, and as such, the mysterious Digimon that was born from it is an extremely dangerous being. It multiplies like a virus within the Computer Network, causing a slight degree of network failure.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Kuramon_b.jpg")
  pabumon = Digimon(name="Pabumon", level="Baby", next_form=["Tanemon", "Yokomon", "Motimon"], bio="Pabumon is a Slime Digimon. Although it looks like it is just pale green bubbles at first glance, it is a Bubble Digimon that can move freely and express a plethora of facial expressions. Because its surface has not hardened yet, its defensive power is nonexistent and it is equally unsuited for combat. From the portion that looks like a pacifier held in its mouth, it generates tiny bubbles, and proliferates them infinitely. As for that proliferation, at one point, it started being used for computer virus development, but because its life force was too weak, that was fortunately never implemented. Although its life is fleeting, it is a lovable Digimon Baby that lives earnestly.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Pabumon_b.jpg")
  pichimon = Digimon(name="Pichimon", level="Baby", next_form=["Bukamon"], bio="Pichimon is a Slime Digimon. As a microorganism-like Digimon which was discovered in the 'Net Ocean', it has the smallest size among a great number of Digimon. Since it seems to be living with nothing but emotions, its actions change very hectically. Due to its curiosity being extremely vigorous, it greatly wishes to communicate with the outside world, but as of yet, no means to do so have been found. However, it is a Digimon Baby that is loved by everyone, due to its big, bright red eyes which are charming enough to shake the opponent's feelings. It spits out soap-like bubbles from its mouth and blinds the opponent's eyes, then flees.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Pichimon_b.jpg")
  poyomon = Digimon(name="Poyomon", level="Baby", next_form=["Tokomon", "Bukamon"], bio="Poyomon is a Slime Digimon. With a translucent body, it is a Digimon Baby that drifts through the 'Net Ocean' like a jellyfish. As it has the most primitive structure among the Digimon discovered to date, it has been showered in attention as the 'Missing Link', the key to solving the mystery of the origin of Digimon, by the scholars and enthusiasts studying the roots of Digimon", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Poyomon_b.jpg")
  punimon = Digimon(name="Punimon", level="Baby", next_form=["Tsunomon", "Nyaromon"], bio="Punimon is a Slime Digimon. It is a new kind of newborn Digimon. Its gelatinous red body is squishy, and there are three feeler-like things growing on its head. It is unable to battle, but it can produce resilient, acidic bubbles to intimidate its opponents.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Punimon_b.jpg")
  yukimiBotamon = Digimon(name="YukimiBotamon", level="Baby", next_form=["Nyaromon"], bio="YukimiBotamon is a Slime Digimon. It is a Baby Digimon whose whole body is covered in fluffy, white hair. It is considered a species of Botamon, and was named 'YukimiBotamon' after its white body, but the details are not clearly known. It is weak to heat, and tends to prefer cold places, so its body feels cold to the touch. When YukimiBotamon exhales, the moisture in the air freezes, and falls while brilliantly glittering.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/YukimiBotamon_b.jpg")
  yuramon = Digimon(name="Yuramon", level="Baby", next_form=["Tanemon"], bio="Yuramon is a Seed Digimon. Its whole body is covered in a substance with the appearance of long, soft hair. When it hatches from its Digi-Egg, it seeks an environment suitable for its growth, and drifts lightly through the air, like a dandelion seed. If it finds a place where there will be no intruders and where the environment is good, it will settle to the ground and begin preparations for Digivolution. Its offensive ability is practically nil.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Yuramon_b.jpg")
  zerimon = Digimon(name="Zerimon", level="Baby", next_form=["Gummymon"], bio="Zerimon is a Slime Digimon. Zerimon and Conomon are extremely rare Digimon, which are born in pairs from a single Digi-Egg. Why only Zerimon and Conomon are born as twins is not clearly known at the present stage. What is more, they are not restricted to always being born as twins, and either a Zerimon or Conomon may be born from a single Digi-Egg. Compared to the extremely energetic, one-horned Zerimon, the three-horned Conomon has a relatively docile personality. Also, unlike other Slime Digimon, Zerimon is perfectly firm other than just the horn on its head. Like other Fresh Digimon, it spits acid bubbles to intimidate opponents.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Baby/Zerimon_b.jpg")

  ###  In-Training  #############################################################################
  # argomonI = Digimon(name="Argomon(In-Training)", level="In-Training", previous_form = ["Argomon(Baby)"], next_form=["Argomon(Rookie)"], bio="Argomon (In-Training) is a Mutant Digimon. It is the form that a newborn Argomon grows into. It is attached to places where large volumes of data flow and consumes that data through the mouth on its underside. It is a creepy one-eyed Digimon with a green body and tentacles that stretch out like arms. Since it's In-Training, it's still very weak, but it's up to some sort of evil and bringing a bad influence to the Real World...!", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/600px-Algomon_baby2.jpg")
  # kapurimon = Digimon(name="Kapurimon", level="In-Training", previous_form = ["MetalKoromon"], next_form=["Kokuwamon", "Kotemon", "Hagurumon", "PawnChessmon(Black)"], bio="Kapurimon is a Lesser Digimon. It is a tiny Digimon wearing a metallic helmet. Within the two horns attached to its helmet, it has antennae that are able to receive any radio wave or sound. Kapurimon is in possession of bat-like traits, as it has weak eyesight, and produces ultrasonic waves from its mouth, recognizing the objects ahead of it from the rebounding sound wave. For that reason, Kapurimon is able to act irrespective of day or night. Among In-Training Digimon, it has superior durability.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Kapurimon_b.jpg")

  arcadiamonI = Digimon(name="Arcadiamon(In-Training)", level="In-Training", previous_form = ["Kuramon"], next_form=["Arcadiamon(Rookie)"], bio="Arcadiamon (In-Training) is a Digimon. It is a Digimon artificially created from the data of various Digimon. One result of an experiment to make the ultimate Digimon, it boasts amazing physical abilities despite being In-Training level. Arcadiamon demonstrates predatory behaviour. By directly absorbing the data of others, Arcadiamon achieves growth at an astounding rate.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Arkadimon_baby2.jpeg")
  bukamon = Digimon(name="Bukamon", level="In-Training", previous_form = ["Poyomon", "Pichimon"], next_form=["Otamamon", "Gomamon", "Syakomon", "Betamon", "Veemon", "SnowGoblimon", "ClearAgumon", "Gumdramon"], bio="Bukamon is a Lesser Digimon. Although it has an appearance which is thought to be the infancy of an aquatic dinosaur, it is a funny Digimon with movements as clever as the seahorse. However, the friendly personality it had as Pichimon has totally vanished, and it quickly flees if others approach. Its outer skin cannot yet bear the water pressure and low temperature of the deep sea, so the length of time it can dive to the deep sea is not long.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Bukamon_b.jpg")
  kokomon = Digimon(name="Kokomon", level="In-Training", previous_form = ["Conomon"], next_form=["Lopmon", "DemiDevimon", "ToyAgumon(Black)", "Shamamon", "Wormmon"], bio="Kokomon is a Lesser Digimon. It grew up from Conomon. The personalities of the robust-natured Gummymon and the docile Kokomon are opposites, but they get along very well, and always act in unison. It is an existence of unified mind and flesh, such that if you temporarily separate the two, it will weaken due to too much loneliness.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Kokomon_b.jpg")
  koromon = Digimon(name="Koromon", level="In-Training", previous_form = ["Botamon"], next_form=["Agumon", "Guilmon", "ToyAgumon", "Dracomon", "Hackmon", "Shoutmon"], bio="Koromon is a Lesser Digimon. It is a tiny Digimon that shed the fuzz covering its surface, and whose body grew even bigger. Although it has become able to move around more actively, it is still unable to battle. It can produce bubbles from its mouth to intimidate opponents.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Koromon_b.jpg")
  motimon = Digimon(name="Motimon", level="In-Training", previous_form = ["Pabumon"], next_form=["Gotsumon", "Solarmon", "Tentomon", "Hagurumon"], bio="Motimon is a Lesser Digimon. It possesses elastic skin, and is a soft-bodied Digimon that uses the protuberances on the underside of its body to toddle about. It came to be called 'Motimon' from inflating its body when it gets worked up, causing it to look like mochi. However, as a result of possessing a height of intelligence that couldn't even be imagined from its appearance, its origin is conjectured to derive from a computer's dictionary feature. It understands human languages, and it is sometimes seen freely deforming its body like it's trying to return communications.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Motimon_b.jpg")
  nyaromon = Digimon(name="Nyaromon", level="In-Training", previous_form = ["Punimon", "YukimiBotamon"], next_form=["Armadillomon", "Terriermon", "Salamon", "Lunamon"], bio="Nyaromon is a Lesser Digimon. It is a tiny Digimon which has cat-like characteristics. It is always capricious, and that behavior seems to have been attached to Nyaromon as a result of its being like a 'cat'. Although it is sometimes frivolous due to its overflowing curiosity, it also has a lonely side.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Nyaromon_b.jpg")
  pagumon = Digimon(name="Pagumon", level="In-Training", previous_form = ["Kuramon"], next_form=["Impmon", "Gazimon", "Chuumon", "Lopmon"], bio="Pagumon is a Lesser Digimon. This small Digimon can fly at low altitudes with the ear-like protrusions growing out of its head. It can move these ears like a second pair of hands, using them to mock the enemy with all kinds of gestures. It has a malicious streak, often chasing after Digimon like Koromon or Tsunomon and teasing them.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Pagumon_b.jpg")
  tanemon = Digimon(name="Tanemon", level="In-Training", previous_form = ["Pabumon", "Yuramon"], next_form=["Palmon", "FanBeemon", "Lalamon", "Renamon"], bio="Tanemon is a Bulb Digimon. It has something that looks like a plant sprout burgeoning from its head. It is a Yuramon that wandered in search of an optimal environment, then settled to the ground and digivolved. Due to its extremely timid personality, if it senses an intruder's presence, it will burrow with the four feet at the base of its body, and completely bury its body portion under the ground. Once it is completely hidden underground, the thing growing from its head assumes the camouflage of a plant, allowing it to defend its body from intruders. However, this is ineffective against herbivorous Digimon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Tanemon_b.jpg")
  tokomon = Digimon(name="Tokomon", level="In-Training", previous_form = ["Poyomon"], next_form=["Patamon", "Falcomon", "Hawkmon", "Lucemon", "Sistermon Blanc"], bio="Tokomon is a Lesser Digimon. It is a tiny Digimon which has limb-like objects growing under its body (head?). In-Training Digimon that have grown limbs are extremely rare, and their appearance is enormously cute. However, while it may be cute, you have to be careful, because if you carelessly stretch out your hand, it will suddenly open its mouth wide, and snap at you with the fangs growing closely packed within. Having said that, because its personality is very innocent, any malice is nonexistent", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Tokomon_b.jpg")
  tsumemon = Digimon(name="Tsumemon", level="In-Training", previous_form = ["Kuramon"], next_form=["BlackAgumon", "Keramon", "Dracmon", "DemiDevimon"], bio="Tsumemon is an Unidentified Digimon. It digivolved further from Kuramon. The tips of its feelers have become claw-shaped, and it has grown even more ferocious. It corrodes data at a tremendous speed, and causes malfunctions in the Network. Also, because its speed of movement is so swift, once it digivolves to Tsumemon, it becomes even harder to capture.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Tsumemon_b.jpg")
  tsunomon = Digimon(name="Tsunomon", level="In-Training", previous_form = ["Punimon"], next_form=["Gabumon", "Gabumon(Blk)", "Goblimon", "Zubamon", "Veemon", "Monodramon"], bio="Tsunomon is a Lesser Digimon. It is a tiny Digimon that hardened one of the feelers on its head as Punimon. From Punimon, it has accomplished a more animal-like Digivolution, and is covered in tufty body hair. It is still at the peak of playfulness, and it has a prank-loving personality, but its combat instinct has not awakened.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Tsunomon_b.jpg")
  wanyamon = Digimon(name="Wanyamon", level="In-Training", previous_form = ["Botamon", "Dodomon"], next_form=["Dorumon", "Gaomon", "Kudamon", "Ryudamon"], bio="Wanyamon is a Lesser Digimon. It is a Digimon fused from the data of small, pet animals like dogs and cats. Because its unexpected movements are also quick, caution is necessary so that it doesn't get away, but it becomes very emotionally attached if shown affection like a pet.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Wanyamon_b.jpg")
  yokomon = Digimon(name="Yokomon", level="In-Training", previous_form = ["Pabumon"], next_form=["Elecmon", "Biyomon", "Mushroomon", "Wormmon"], bio="Yokomon is a Bulb Digimon. It is a Lesser Digimon with a large flower blooming from its head. It is able to move by skillfully operating its root-like tentacles, and with its lightness, it can rise into the air, but only to a small height. As it is brimming with curiosity, it is restlessly stirring and its appearance seems very cute. It has a habit of living together in flocks, and it is said that due to grouping, the flocks will grow from a few to a few hundred.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Yokomon_b.jpg")
  gigimon = Digimon(name="Gigimon", level="In-Training", previous_form = ["Jyarimon"], next_form=["Guilmon", "Goblimon", "Solarmon", "Gotsumon"], bio="Gigimon is a Lesser Digimon. It is a four-legged Digimon that grew from Jyarimon. Its physical features resemble those of Tokomon, and there are powerful fangs growing within its mouth. However, unlike Tokomon, who digivolves into the Mammal-species, Gigimon, who digivolves into the Dragon-species, has a rough personality, and is ferocious despite its small size. There are more than a few even larger Digimon that were deceived by its appearance and suffered a counterattack. The temperature of its bites are hot like with Jyarimon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Gigimon_b.jpg")
  gummymon = Digimon(name="Gummymon", level="In-Training", previous_form = ["Zerimon"], next_form=["Terriermon", "ToyAgumon", "ClearAgumon", "Hagurumon", "Gaomon", "Shoutmon"], bio="Gummymon is a Lesser Digimon. It grew up from Zerimon. As it inherited an exceedingly energetic personality from Zerimon, it is both cheerful and lively. Although it is growing, it's squishy because its body tissue is as unstable as usual, but just like Zerimon, its horn portion has hardened, and it intimidates the opponent with headbutts. Its greatest change from Zerimon is that it has a body and ear-like objects coming out of its head.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/In-Training/Gummymon_b.jpg")

  ###   Rookie     ################################################################################
  # argomonR = Digimon(name="Argomon(Rookie)", level="Rookie", previous_form = ["Argomon(In-Training)"], next_form=["Argomon(Champion)"], bio="Argomon (Rookie) is a Mutant Digimon. It is the Rookie-digivolved form of Argomon. It watches over young Argomon that are consuming data, and intercepts enemies when they draw near.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Argomon_(Rookie)_b.jpg")
  # floramon = Digimon(name="Floramon", level="Rookie", previous_form = ["Tanemon"], next_form=["Kiwimon", "Ninjamon", "Vegiemon"], bio="Floramon is a Vegetation Digimon. Although it has digivolved like a reptile, just like Palmon, it is categorized as an unusual Digimon of the Vegetation type. Its whole face has the appearance of a flower, and the petal-styled shell usually protects its head like a helmet. When intruders are not around or when it's in a good mood, the petals on its head and both of its arms open up wide. It sees Palmon as its rival, and has a very prideful personality.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Floramon_b.jpg")
  # kokuwamon = Digimon(name= "Kokuwamon", level="Rookie", previous_form = ["Kapurimon"], next_form=["Guardromon", "Thundermon"], bio="Kokuwamon is a Machine Digimon. It is a very unusual Insect Mecha-Digimon that was recently discovered. Insect Mecha-Digimon had not been discovered until now, and their existence itself was never even imagined. Because it will discharge 100 megavolts of electricity from both of its arms and the stun gun-shaped head it possesses if it senses danger, you mustn't carelessly approach. However, it has not an aggressive personality, but a docile personality which seeks tranquility. It uses electricity as its source of nutrients, and charges electric power using its middle two legs.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Kokuwamon_b.jpg")
  # kotemon = Digimon(name= "Kotemon", level="Rookie", previous_form = ["Kapurimon"], next_form=["Dinohyumon", "Musyamon", "Gladiamon", "Omekamon", "PlatinumSukamon"], bio="Kotemon is a Reptile Digimon. It is a Digimon that practices kendo with a bamboo sword. Although it doesn't say much, this Digimon works hard in the background. It never removes its armor, and no one has ever seen its true face.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Kotemon_b.jpg")
  # pawnChessmonb = Digimon(name="PawnChessmon(Black)", level="Rookie", previous_form = ["Kapurimon"], next_form=["KnightChessmon(Black)"], bio="PawnChessmon (Black) is a Puppet Digimon. It was born from data leaking out of a chess game supercomputer. Its power is weak, but it is promoted when it strives for prominence, and it is an ordinary pawn that conceals the mystery that it is said to possess Mega-class power. Its catchphrase is, 'I only advance!' It considers its fellows who are striving for prominence ahead of it to be its rivals, among them PawnChessmon (White).", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/PawnChessmon_(Black)_b.jpg")

  agumonB = Digimon(name="Agumon(Black)", level="Rookie", previous_form = ["Koromon", "Tsumemon"], next_form=["Cyclonemon", "Fugamon", "Greymon(Blue)", "Growlmon", "Monochromon", "Saberdramon", "Tankmon", "Tyrannomon"], bio="Agumon(Black) is a Reptile Digimon. It has grown up and become able to walk on two legs, and has an appearance like a tiny dinosaur. Because it is still on the way to adulthood, its power is low, but as its personality is quite ferocious, it doesn't understand fear. It has grown hard, sharp claws on its hands and feet, and demonstrates its power in battle. It is also a being that foretells digivolution to a great and powerful Digimon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/BlackAgumon_b.jpg")
  biyomon = Digimon(name="Biyomon", level="Rookie", previous_form = ["Yokomon"], next_form=["Birdramon", "Aquilamon", "Kokatorimon"], bio="Biyomon is a Bird Digimon. Its wings have developed to become like arms and it is able to dexterously operate them and use them to grip objects, but for that reason, it is poor at flying through the air. It usually lives on the ground, but when danger draws near, it escapes by flying away. However, since its flying ability is on the same level as Patamon, it sees Patamon as its rival. Its dream is to someday become Birdramon, who can fly freely about the sky, and it seems it doesn't want to become Kokatorimon, who cannot fly at all. As its personality is to be brimming over with curiosity, it loves to peck at the head portion of Tanemon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Biyomon_b.jpg")
  chuumon = Digimon(name="Chuumon", level="Rookie", previous_form = ["Pagumon"], next_form=["Tyrannomon"], bio="Chuumon is an Animal Digimon. It is a rat-like Digimon that is always feeding Sukamon with unscrupulous thoughts. It has forged a strong friendship with Sukamon (that said, it might be only Chuumon that thinks this?), after a past incident where Chuumon was caught in a Carnivore system trap placed on the Network, and was saved by Sukamon who just happened to be passing by. While it is generally cowardly, its cunning is unparalleled and it will dash away to safety at the first sign of danger. Chuumon does not fight and is always coaxing Sukamon into performing bad deeds.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Chuumon_b.jpg")
  demiDevimon = Digimon(name="DemiDevimon", level="Rookie", previous_form = ["Pagumon", "Tsumemon", "Tanemon", "Kokomon"], next_form=["Devimon", "Bakemon", "Soulmon", "IceDevimon", "Kyubimon", "Chrysalimon", "BlackGatomon"], bio="DemiDevimon is an Evil Digimon. It is a tiny familiar Digimon which has an appearance like a bat. It exists to serve as a familiar for higher-class Demon Digimon like Devimon and Myotismon, but it is also said to be the one responsible for tempting Devimon, who was an angel-species Digimon, and luring it to the Dark Side. Its personality is the epitome of a Dark Side Digimon, so although its offensive ability and the like are not strong, it is cunning and makes mischief all over, but it seldom voluntarily takes part in anything like direct combat. When it absolutely must fight, it uses its Special Move 'Demi Dart'. It prefers the dark, and is often with a higher-level Digimon at all times, so it seems that it is seldom observed on its own.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/DemiDevimon_b.jpg")
  hagurumon = Digimon(name= "Hagurumon", level="Rookie", previous_form = ["Motimon", "Kapurimon"], next_form=["Guardromon", "Mekanorimon"], bio="Hagurumon is a Machine Digimon. It is a mutant Digimon shaped like a gear. There are countless gears built into its body, and the gears are constantly rotating. For that reason, if even a single gear is missing, all of the gears in its body stop rotating, and it becomes unable to maintain its vital functions. Hagurumon possesses the special ability to send a computer virus to its opponents in order to manipulate them at will, and that ability is exploited by fiendish Digimon. However, because Hagurumon itself doesn't have any sense of self, it doesn't even know it is being misused.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Hagurumon_b.jpg")
  mushroomon = Digimon(name="Mushroomon", level="Rookie", previous_form = [], next_form=["Woodmon"], bio="Mushroomon is a Vegetation Digimon. It is a tiny Digimon in the shape of a poisonous mushroom. It grows tiny mushroom bombs, powerful with toxins that induce every affliction, out of its body. If one gets hit with these mushroom bombs, they become unable to stop laughing, their body becomes completely paralyzed, all of their memories until then vanish, and they start showing various symptoms. As its personality is extremely ill-tempered, it loves to bully the weak, but it has a shy side, and always conceals half of its face.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Mushroomon_b.jpg")
  palmon = Digimon(name="Palmon", level="Rookie", previous_form = ["Tanemon"], next_form=["Togemon", "Woodmon"], bio="Palmon is a Vegetation Digimon. It has a tropical flower blooming on its head. Although it digivolved like a reptile from Tanemon, it is an unusual Type which is classified as Vegetation based on its outward appearances and special qualities, similar to its rival Floramon. As a Vegetation Digimon, it gets along with FanBeemon. During the day, it opens up the flower and spreads its leaf-like arms to perform photosynthesis. It usually buries its root-like feet under the ground, and although it is absorbing nutrients, it is also able to walk. As for the flower on its head, when it is joyful or happy, it will waft about a sweet fragrance, but when it is angered or senses danger, it releases a foul stench that will drive off even large Digimon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/Palmon_b.jpg")
  toyAgumonb = Digimon(name="ToyAgumon(Black)", level="Rookie", previous_form = ["Kokomon", "Tsumemon"], next_form=["Guardromon", "Nanimon", "Fugamon", "Greymon(Black)"], bio="ShadowToyAgumon is a Puppet Digimon. It is a ToyAgumon that has been dyed black. It was infected by a computer virus within the Network, and turned into a toy that would bully children instead.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Rookie/ShadowToyAgumon_b.jpg")

  ###   Champion   ################################################################################
  argomonC = Digimon(name="Argomon(Champion)", level="Champion", previous_form = ["Argomon(Rookie)"], next_form=["Argomon(Ultimate)"], bio="Argomon (Champion) is a Mutant Digimon. It is the Champion-digivolved form of Argomon whose processing ability has increased abnormally. Its power has also strengthened, and it lifts up huge enemies with its arms, which have turned into industrial manipulators.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Argomon_(Champion)_b.jpg")
  guardromon = Digimon(name="Guardromon", level="Champion", previous_form = ["Kokuwamon", "ToyAgumon(Black)", "Hagurumon"], next_form=["Andromon"], bio="Guardromon is a Machine Digimon. It is a Machine Digimon that protects the computer network's defense wall. It originally worked with the 'Net Keeper' Giromon to repulse those who would illegally enter through the defense wall. However, malicious hackers noticed its ironclad defensive ability and infected Guardromon with a computer virus, using it to protect themselves from the vaccine-type justice brigade known as the 'Virus Busters.' Because its program commands are basically purely defensive in nature, the change in allegiance to defending the intruders did not pose a huge problem for Guardromon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Guardromon_b.jpg")
  kiwimon = Digimon(name="Kiwimon", level="Champion", previous_form = ["Floramon"], next_form=["Sinduramon", "Blossomon"], bio="Kiwimon is an Ancient Bird Digimon. A mythical, ancient Digimon that was said to have been overhunted to extinction due to the spread of the Internet. Although it is a Bird Digimon, its wings have completely degenerated so it is unable to fly in the air. Furthermore, it possesses the makeup of a Plant-type and is able to perform photosynthesis with the leaf-like things growing on its head, providing itself with nourishment. It has no other ways of defending itself aside from the hard shell that covers its head, and it is easily attacked by intruders due to its docile personality.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Kiwimon_b.jpg")
  kogamon = Digimon(name="Ninjamon", level="Champion", previous_form = [], next_form=["Cherrymon"], bio="Kogamon is a Mutant Digimon. It is a shinobi Digimon who dons a purple mask and lives in the darkness. It is in the midst of travelling the Digital World in order to hone its Kouga-style ninjutsu. It is rarely encountered as it often moves from shadow to shadow in order to avoid being seen by others.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Kogamon_b.jpg")
  kokatorimon = Digimon(name="Kokatorimon", level="Champion", previous_form = ["Biyomon"], next_form=["Megadramon", "Sinduramon"], bio="Kokatorimon is a Bird Digimon. It has two overdeveloped legs, and because it has continued to live on the ground for so long, it cannot fly through the air, and has digivolved a body that is suited for land. For that reason, its body became even larger, and its leg strength has developed tremendously, as well. Its wing portions have completely degenerated, and in battles, it spreads them wide along with its tail to intimidate the opponent. Its disposition is violently ferocious, but in order to preserve its large build, it avoids violent battles that consume its energy.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Kokatorimon_b.jpg")
  kuwagamon = Digimon(name="Kuwagamon", level="Champion", previous_form = [], next_form=["Megadramon", "Okuwamon"], bio="Kuwagamon is an Insectoid Digimon. It is armed with gigantic pincers on its head. Like Kabuterimon, it has combat abilities that far exceed those of similar species that inhabit File Island. It is protected by its tenacious power and sturdy shell, and in particular, as the power of its pincers is super-powerful, once it clamps an enemy, it will squeeze until the opponent's life is extinguished. There is a perfect rivalry between it and the Vaccine-attribute Kabuterimon, and there is only 'Conflict' between them.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Kuwagamon_b.jpg")
  mekanorimon = Digimon(name="Mekanorimon", level="Champion", previous_form = ["Hagurumon"], next_form=["Megadramon"], bio="Mekanorimon is a Machine Digimon. It is a Powered Suit Digimon used exclusively by tiny Digimon, and is the first Vehicle Digimon in the Digital World. It is a unique Digimon that is unable to move on its own and is incapable of action unless it is being piloted by another Digimon. Considering its Virus attribute, the pilot Digimon can probably be considered a Virus attribute, too. It is a Digimon that is still in development, and if it is overworked then its computer kernel will totally overheat.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Mekanorimon_b.jpg")
  ninjamon = Digimon(name="Ninjamon", level="Champion", previous_form = ["Floramon"], next_form=["Blossomon", "Cherrymon"], bio="Ninjamon is a Mutant Digimon. It is a mysterious Digimon wearing a red mask. It is wandering the Digital World and building its training. It is a master of espionage, and if it is hiding within the trees of a forest, or hiding underwater, catching sight of its figure is considerably difficult. Also, although it differs in school and doctrine from Deputymon, who is also one of the 'Virus Busters', they are comrades in arms since olden times, and are also good rivals.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Ninjamon_b.jpg")
  togemon = Digimon(name="Togemon", level="Champion", previous_form = ["Palmon"], next_form=["Lillymon"], bio="Togemon is a Vegetation Digimon. It has the appearance of a gigantic cactus. It can store nutrient data within its body, and can even survive for a long time in the empty desert areas. What it's thinking usually can't be understood at all by trying to discern it from its facial expression, as it spends most of the day staring off into space. However, once Togemon is angered, that expression changes completely, it starts getting violent, and it becomes unable to settle down. According to one theory, Togemon was originally a 'Plant Weapon' used when a Vademon that was discovered and captured near a certain country's 'Area 51' invaded the planet, and was said to have started advancing toward every strategic base. However, as usual, Togemon's mysterious behavior has turned the truth into a mystery. Also, its connection to the rumor that Vademon was born from the 'seed of a plant' is currently being studied.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Togemon_b.jpg")
  tyrannomon = Digimon(name="Tyrannomon", level="Champion", previous_form = ["Agumon(Black)", "Chuumon"], next_form=["MetalTyrannomon", "MasterTyrannomon", "Megadramon", "SkullGreymon"], bio="Tyrannomon is a Dinosaur Digimon. It is a Digimon shaped like an ancient dinosaur from prehistoric times. Its two developed arms and massive tail mow down everything. It has intelligence and a docile personality, so it's easy to tame. This makes it handy for fledgling tamers, and many will raise one with care. It can be considered a fundamental Digimon representative. There is a rivalry between it and fellow Dinosaur Digimon, Allomon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Tyrannomon_b.jpg")
  woodmon = Digimon(name="Woodmon", level="Champion", previous_form = ["Mushroomon", "Palmon"], next_form=["Cherrymon", "Argomon(Ultimate)"], bio="Woodmon is a Vegetation Digimon. Woodmon is shaped like a giant, withered tree. It's made of normal wood, and lives by grabbing passing Digimon and draining their energy. It can also move around on its root-like feet. Violent by nature, it will attack relentlessly when angered. Its strong tree trunk gives it high defense but weakness against fire. This makes it weak against fire Digimon like Meramon or Birdramon, which it regards as enemies.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Champion/Woodmon_b.jpg")

  ###   Ultimate   ################################################################################
  argomonU = Digimon(name="Argomon(Ultimate)", level="Ultimate", previous_form = ["Argomon(Champion)", "Woodmon"], next_form=["Argomon(Mega)"], bio="Argomon (Ultimate) is a Mutant Digimon. It is a powerful dark Digimon that was generated from a bug in an algorithm. Due to its ability for high speed processing, it uses its countless ivy tendrils as tentacles, taking complete control of a vast field. The eyes on its head are always closed, and its arms can be transformed to become wings and tentacles for close combat.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Ultimate/Argomon_%2528Worm_Phase%2529_dm.png")
  blossomon = Digimon(name="Blossomon", level="Ultimate", previous_form = ["Ninjamon", "Kiwimon"], next_form=["Gryphonmon"], bio="Blossomon is a Vegetation Digimon. It has the appearance of a giant flower, with countless vines as its roots growing from its body. Despite its strange appearance it is very docile, and due to its personality it rarely appears before others. For a plant it has an unusually long life span, and although the petals around its body (or face, really) fall out whenever the seasons change, it has the special ability to grow back new petals. It hates arid regions, and always inhabits areas near the water.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Ultimate/Blossomon_b.jpg")
  cherrymon = Digimon(name="Cherrymon", level="Ultimate", previous_form = ["Woodmon", "Ninjamon", "Kogamon"], next_form=["Puppetmon", "Ghoulmon"], bio="Cherrymon is a Vegetation Digimon. Woodmon digivolved further, and as Cherrymon, it is a Digimon that has acquired extremely elevated intelligence and power. Called the 'Lord of the Deep Forest', it is a terrifying Digimon who tempts Digimon who have gone astray in the dark deep forest to go further and deeper into the woods, so that they will never break out of that forest. The fog it generates from its body displays illusions, tempting the opponent into the forest depths, where it uses its branches like tentacles and ivy to capture the opponent for its own nutrition. If you notice a Woodmon that has lived a long life, it is probably wise to fell it before it digivolves to Cherrymon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Ultimate/Cherrymon_b.jpg")
  lillymon = Digimon(name="Lillymon", level="Ultimate", previous_form = ["Togemon"], next_form=["Rosemon", "MarineAngemon", "BanchoLillymon"], bio="Lillymon is a Fairy Digimon. It was born from beautifully blooming flower petals, and as a Plant Digimon, it gets along with FanBeemon. Although it looks like it has an appearance like a human child, it is an Ultimate Digimon hiding unfathomable power within. Due to its whimsical, tomboyish personality, it is said that it will open its heart to a human girl with a similar temperament. Also, because it becomes unable to settle down if it starts crying like a crybaby, a great effort is necessary to win it over. However, it also has an aspect that kindly extends its hand to small or weak things. It can fly in the air with the four leaf-like wings growing from its back, and it is said that after Lillymon flies by, a fresh breeze will blow.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Ultimate/Lillymon_b.jpg")
  megadramon = Digimon(name="Megadramon", level="Ultimate", previous_form = ["Mekanorimon", "Kokatorimon", "Kuwagamon", "Tyrannomon", "Monochromon"], next_form=["Ghoulmon", "Machinedramon"], bio="Megadramon is a Dark Dragon Digimon. It is a member of the Crack Team and was remodeled for anti-air use at the same time as Gigadramon, incorporating technology appropriated from Andromon. It is a dark dragon Digimon that is said to boast the strongest and wickedest power among Dragon-type Cyborg Digimon of the Ultimate level. As a Digimon that was artificially remodeled by someone, it was programmed to destroy everything. It can definitely be said that its existence is the epitome of a computer virus. It can easily penetrate Computer Networks protected by strong security, and can very easily destroy and then completely reformat the host computer.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Ultimate/Megadramon_b.jpg")

  ###   Mega       ################################################################################
  ancientTroiamon = Digimon(name="AncientTroiamon", level="Mega", previous_form = ["Puppetmon"], next_form = ["Apocalymon"], bio='AncientTroiamon is an Ancient Plant Digimon. Possessing the attribute of "Wood", it is one of the Ten Legendary Warriors that saved the ancient Digital World. A Mega who existed only in the distant past, it boasts of the greatest size among the Ancient Digimon. Various mechanisms are set within its body and it displays tricky attacks and movements. Its abilities were later passed on to the "Plant Digimon".', photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/AncientTroiamon_b.jpg")
  apocalymon = Digimon(name="Apocalymon", level="Mega", previous_form = ["AncientTroiamon", "Chaosdromon", "GigaSeadramon"], next_form = ["Mephistomon"], bio='Apocalymon is an Unidentified Digimon. It is a Digimon who appeared when negative thoughts were drawn together by darkness. So little is known about Apocalymon that it may not even be a Digimon. Some claim it appeared to purge the chaos of cyberspace, and reduce it back to nothing; others claim its arrival was spoken of in ancient texts.', photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Apocalymon_b.jpg")
  argomonM = Digimon(name="Argomon(Mega)", level="Mega", previous_form = ["Argomon(Ultimate)"], bio="Argomon (Mega) is a Mutant Digimon. It is a gigantic Mega Digimon that digivolved from the Ultimate Argomon, and also amplified its close-combat abilities. Its eyes, which were closed, are now open and its power is unleashed.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Argomon_(Mega)_b.jpg")
  banchoLillymon = Digimon(name="BanchoLillymon", level="Mega", previous_form = ["Lillymon"], bio="BanchoLillymon is a Fairy Digimon. It is a crimson tokkō-fuku wearing Digimon. The gorgeous petals it had in the days it was a Lillymon have been dyed a dark color, and the pretty impression it made is long gone. In a Digital World of the survival of the fittest, it believes in fighting for the underdog, having saved a lot of those who were attacked by evil Digimon. It was awarded the title of 'Bancho' when it donned its tokkō-fuku, a testament to its beliefs.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/BanchoLillymon_b.jpg")
  ghoulmon = Digimon(name="Ghoulmon", level="Mega", previous_form = ["Cherrymon", "Megadramon"], bio="Ghoulmon is a Demon Lord Digimon. Like Daemon, it was originally a high-ranking Angel Digimon, but it fell to the Dark Area and is now one of the Demon Lord Digimon. Even though it is a Demon Lord Digimon, it is different from other Fallen Angel and Devil Digimon in that it does not run the whole gamut of wickedness, but instead does its utmost to carefully maintain a position of neutrality; despite this, it is easily manipulated by the cunning Barbamon. However, it is a terrifying Digimon, and it is told that at the time of the approaching final battle, that whitened appearance will change to jet-black darkness, and it will transform into a god of destruction.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Ghoulmon_b.jpg")
  gryphonmon = Digimon(name="Gryphonmon", level="Mega", previous_form = ["Blossomon", "Hippogriffomon"], bio="Gryphonmon is a Mythical Animal Digimon. It is a fusion Digimon which possesses the head, wings, and forelegs of a Bird Digimon, and the body of a Beast Digimon with a snake-like tail attached to it. Although it is able to fly about the skies with its wings, it is said that it usually inhabits desert regions and mountain caves. Also, Gryphonmon's offensive power is extremely great, and because it makes sport of enemies with its keen movements, it is difficult to analyze any way to defeat Gryphonmon. To make the best use of those abilities, it serves as a guard defending against illegal penetrations of the Internet, and is used for the security of confidential information. A Gryphonmon attends Murmukusmon, who uses it as its hands and feet.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Gryphonmon_b.jpg")
  marineAngemon = Digimon(name="MarineAngemon", level="Mega", previous_form = ["Lillymon", "Whamon"], bio="MarineAngemon is a Pixie Digimon. Since it inhabits the Net Ocean, its figure can rarely be seen. Although it possesses the name of 'Angemon', as far as the ecosystem is concerned, the Angemon-species is actually a different family. It wears a Holy Ring around its neck. Although it fundamentally dislikes combat, its Special Move 'Kahuna Waves' results in it achieving victory.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/MarineAngemon_b.jpg")
  puppetmon = Digimon(name="Puppetmon", level="Mega", previous_form = ["Cherrymon"], next_form = ["AncientTroiamon"], bio="Puppetmon is a Puppet Digimon. It was built from the body of a cursed Cherrymon, and it is thought that it was probably constructed from Cherrymon's data by a single fiendish hacker. It has an appearance like a marionette, but it can move under its own volition. Its personality is detestable, as it tells fibs, and when a computer presents false information, it is the work of Puppetmon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Puppetmon_b.jpg")
  rosemon = Digimon(name="Rosemon", level="Mega", previous_form = ["Lillymon", "Lilamon"], next_form = ["Babamon", "Rosemon Burst Mode", "Rafflesimon"], bio="Rosemon is a Pixie Digimon. It has an appearance like the rose, which is said to be the queen of flowers. It has the appearance of a beautiful woman, and desires to remain beautiful forever. Its personality is more or less that way, and though it is excessively self-conscious about such things, its true strength does not in fact compare unfavorably with other Megas. It wears on its breast a 'Tifaret', a jewel which is engraved with the symbol of love and beauty, that is said to promise it eternal beauty and power. It is whispered that a Rosemon was placed under a spell and turned into Babamon.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Digimon/Mega/Rosemon_b.jpg")


  # db.session.add(argomonB)
  # db.session.add(chibomon)
  # db.session.add(dodomon)
  # db.session.add(keemon)
  # db.session.add(ketomon)
  # db.session.add(metalkoromon)
  # db.session.add(mokumon)

  db.session.add(botamon)
  db.session.add(conomon)
  db.session.add(jyarimon)
  db.session.add(kuramon)
  db.session.add(pabumon)
  db.session.add(pichimon)
  db.session.add(poyomon)
  db.session.add(punimon)
  db.session.add(yukimiBotamon)
  db.session.add(yuramon)
  db.session.add(zerimon)

  # db.session.add(argomonI)
  # db.session.add(kapurimon)

  db.session.add(arcadiamonI)
  db.session.add(bukamon)
  db.session.add(gigimon)
  db.session.add(gummymon)
  db.session.add(kokomon)
  db.session.add(koromon)
  db.session.add(motimon)
  db.session.add(nyaromon)
  db.session.add(pagumon)
  db.session.add(tanemon)
  db.session.add(tokomon)
  db.session.add(tsumemon)
  db.session.add(tsunomon)
  db.session.add(wanyamon)
  db.session.add(yokomon)

  # db.session.add(argomonR)
  # db.session.add(floramon)
  # db.session.add(kokuwamon)
  # db.session.add(kotemon)
  # db.session.add(pawnChessmonb)

  db.session.add(biyomon)
  db.session.add(agumonB)
  db.session.add(chuumon)
  db.session.add(demiDevimon)
  db.session.add(hagurumon)
  db.session.add(mushroomon)
  db.session.add(palmon)
  db.session.add(toyAgumonb)

  db.session.add(argomonC)
  db.session.add(guardromon)
  db.session.add(kiwimon)
  db.session.add(kogamon)
  db.session.add(kokatorimon)
  db.session.add(kuwagamon)
  db.session.add(mekanorimon)
  db.session.add(ninjamon)
  db.session.add(togemon)
  db.session.add(tyrannomon)
  db.session.add(woodmon)

  db.session.add(argomonU)
  db.session.add(blossomon)
  db.session.add(cherrymon)
  db.session.add(lillymon)
  db.session.add(megadramon)

  db.session.add(ancientTroiamon)
  db.session.add(apocalymon)
  db.session.add(argomonM)
  db.session.add(banchoLillymon)
  db.session.add(ghoulmon)
  db.session.add(gryphonmon)
  db.session.add(marineAngemon)
  db.session.add(puppetmon)
  db.session.add(rosemon)

#################################################################
# Media                                                         #
#################################################################

  da1 = Media(name="Digimon Adventure", type="Tv-Show", bio="Digimon Adventure (デジモンアドベンチャー Dejimon Adobenchā?) is the first season of the anime saga Digimon: Digital Monsters. Its premise involves a group of boys and girls being whisked to a parallel reality called the Digital World, sometimes called 'DigiWorld' for short, while at summer camp. They were taken there because they were chosen to become DigiDestined, the children that would save the Digital World (along with Earth near the end of the series) from the evil forces that threatened to destroy it. Each of the children received a Digimon partner who was preprogrammed to be bonded to them, as well as miniature devices called Digivices. With the power of the Digivices, their Digimon partners could become stronger forms to battle enemies or save their partners from danger. \nAn RPG-retelling of the series was released on the PSP as part of Digimons fifteenth anniversary.\nA reboot anime series titled Digimon Adventure: began airing on April 5, 2020.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Media/Tv-Shows/Digimon_Adventure.jpg")
  kizuna = Media(name="Digimon Adventure: Last Evolution Kizuna", type="Movie", bio="Digimon Adventure: Last Evolution Kizuna (デジモンアドベンチャー LAST EVOLUTION 絆 Dejimon Adobenchā LAST EVOLUTION Kizuna?, lit. 'Digimon Adventure LAST EVOLUTION Bond' is a sequel to Digimon Adventure tri. that premiered in Japanese theaters on February 21, 2020. A dubbed/subbed version was released digitally September 29, 2020.On May 28, 2018, the original Director of Digimon Adventure and Digimon Adventure 02, Hiroyuki Kakudo revealed he had quit the staff of Digimon Adventure: Last Evolution Kizuna after something was approved that he claimed was incompatible with what the previous series had established. On September 20, 2020, Producer Yosuke Kinoshita stated that Digimon Adventure: Last Evolution Kizuna is in continuity with Digimon Adventure, Digimon Adventure 02, Digimon Adventure 02: Digimon Hurricane Landing!!/Transcendent Evolution!! The Golden Digimentals, and Digimon Adventure tri.. This included the end of the final episode of 02, set in 2028, where the DigiDestined are adults.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Media/Movies/Digimon_Adventure_Last_Evolution_Kizuna_poster.jpg")
  cyber_sleuth = Media(name="Digimon Story: Cyber Sleuth", type="Game", bio="Digimon Story: Cyber Sleuth (デジモンストーリー　サイバースルゥース Dejimon Sutōrī: Saibā Surwūsu?) is a Digimon video game for the PlayStation Vita. It is part of the Digimon Adventure 15th Anniversary and an entry in the Digimon Story series. At Anime Expo 2015, a localized release was announced for 2016 through retail for the PlayStation 4 and digitally for the PlayStation Vita. At Anime Expo 2019, a port to Nintendo Switch and Windows PC, alongside its sequel, Digimon Story: Cyber Sleuth - Hacker's Memory, was announced for October 18, 2019, as Digimon Story: Cyber Sleuth Complete Edition, though the PC version released a day early. The Japanese version will release one day earlier, only for Nintendo Switch. The localization retains the Japanese audio track and does not feature an English dub. Cyber Sleuth was followed up two years later with Digimon Story: Cyber Sleuth - Hacker's Memory, a midquel, the story taking place at the same time as the original.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Media/VideoGames/Digimon_Story_Cyber_Sleuth_NTSC_Cover_Art_b.jpg")
  ccg2020 = Media(name="Digimon Card Game(2020)", type="CCG", bio="Digimon Card Game (デジモンカードゲーム Dejimon Kādo Gēmu?) is a card game developed by Bandai Namco. It was released in Japan in April 2020 and will release in English in January 2021 though select stores will hold a pre-sale on November 27, 2020. FUN! DigiCa, a YouTube show promoting the Japanese version of the game, started airing on March 23, 2020.", photo_url="https://digicyclopedia.s3.us-east-2.amazonaws.com/Media/CCGs/118734096_105338024640802_8934784446808492192_n.jpg")

  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")
  # cyber_sleuth = Media(name="", type="Movie", bio="", photo_url="")



  db.session.add(da1)
  db.session.add(kizuna)
  db.session.add(cyber_sleuth)
  db.session.add(ccg2020)
  # db.session.add()

  db.session.commit()
